// Generated by CoffeeScript 1.3.3
(function() {
  var jsdom;

  jsdom = require('jsdom');

  exports.filter = function(html, callback) {
    jsdom.defaultDocumentFeatures = {
      FetchExternalResources: false,
      ProcessExternalResources: false,
      QuerySelector: false
    };
    return jsdom.env(html, function(errors, window) {
      var element, href, localLinkRxp, _i, _len, _ref;
      localLinkRxp = /https?:\/\/blog.busbud.com/i;
      _ref = window.document.getElementsByTagName('*');
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        element = _ref[_i];
        switch (element.tagName) {
          case 'STYLE':
          case 'SCRIPT':
          case 'IFRAME':
            element.parentNode.removeChild(element);
            break;
          case 'LINK':
            if (/stylesheet/i.test(element.getAttribute('rel'))) {
              element.parentNode.removeChild(element);
            }
            break;
          case 'A':
            href = element.getAttribute('href');
            if (localLinkRxp.test(href)) {
              element.setAttribute('href', href.replace(localLinkRxp, '/blog'));
            }
            if (href.indexOf('/') === 0) {
              element.setAttribute('href', '/blog' + href);
            }
        }
        if (element.getAttribute('style')) {
          element.removeAttribute('style');
        }
      }
      return callback(window.document.documentElement.innerHTML);
    });
  };

}).call(this);
