// Generated by CoffeeScript 1.3.3
(function() {
  var rxpStrip;

  rxpStrip = function(text) {
    return text.replace(/<script[^>]*>[\S\s]*?<\/script>/g, '').replace(/<style[^>]*>[\S\s]*?<\/style>/g, '').replace(/<link(rel\s?=['"]\s?stylesheet\s?['"]|[^>])*\/>/g, '').replace(/style\s?=\s?("[^"]*"|'[^']*')/g, '');
  };

  exports.naive = function(input, output) {
    var buffer, end, write;
    write = output.write;
    end = output.end;
    buffer = '';
    output.write = function(buf) {
      return buffer += buf.toString();
    };
    output.end = function(buf) {
      if (buf) {
        buffer += buf.toString();
      }
      return end.call(output, rxpStrip(buffer));
    };
    return input.pipe(output);
  };

}).call(this);
