// Generated by CoffeeScript 1.3.3
(function() {
  var naiveFilter;

  naiveFilter = function(text) {
    return text.replace(/<script[^>]*>[\S\s]*?<\/script>/g, '').replace(/<style[^>]*>[\S\s]*?<\/style>/g, '').replace(/<link(rel\s?=['"]\s?stylesheet\s?['"]|[^>])*\/>/g, '').replace(/style\s?=\s?("[^"]*"|'[^']*')/g, '');
  };

  exports.naiveStrip = function(input, output) {
    var buffer;
    buffer = "";
    input.on('data', function(buf) {
      return buffer += buf.toString();
    });
    return input.on('end', function() {
      output.write(naiveFilter(buffer));
      return output.end();
    });
  };

}).call(this);
