// Generated by CoffeeScript 1.3.3
(function() {
  var Boomerang, express, http, _;

  _ = require('underscore');

  express = require('express');

  http = require('http');

  Boomerang = (function() {

    function Boomerang(options) {
      this.options = options != null ? options : {};
      _(this.options).extend({
        port: 3000
      });
      this.app = express();
      this.server = http.createServer(app).listen(this.options.port, function() {
        return console.log("Boomerang listening on port " + this.options.port);
      });
      this.configure();
    }

    Boomerang.prototype.configure = function() {
      this.app.configure(function() {
        this.app.use(express.logger('dev'));
        return this.app.use(app.router);
      });
      return this.app.configure('development', function() {
        return app.use(express.errorHandler());
      });
    };

    return Boomerang;

  })();

  exports.createServer = function(options) {
    return new Boomerang(options);
  };

}).call(this);
