// Generated by CoffeeScript 1.3.3
(function() {
  var Boomerang, express, filter, http, request, _;

  _ = require('underscore');

  express = require('express');

  http = require('http');

  request = require('request');

  filter = require('./boomerang/filter').filter;

  Boomerang = (function() {

    Boomerang.prototype.proxiedHeaders = ['cache-control', 'user-agent', 'accept', 'accept-language', 'cookie'];

    function Boomerang(options) {
      this.options = options != null ? options : {};
      _(this.options).extend({
        port: 3000
      });
      this.app = express();
      this.server = http.createServer(this.app).listen(this.options.port);
      this.configure();
    }

    Boomerang.prototype.configure = function() {
      var isDevelopment,
        _this = this;
      isDevelopment = process.env['NODE_ENV'] !== 'production';
      this.app.configure(function() {
        if (isDevelopment) {
          _this.app.use(express.logger('dev'));
        }
        _this.app.use(_this.app.router);
        if (isDevelopment) {
          return _this.app.use(express.errorHandler());
        }
      });
      return this.app.all(['/blog', '/blog/*'], this.proxyRequest);
    };

    Boomerang.prototype.proxyRequest = function(req, res) {
      var options, _ref;
      options = {
        uri: 'http://blog.busbud.com' + req.params[0].replace(/\/blog/, ''),
        headers: (_ref = _(req.headers)).pick.apply(_ref, this.proxiedHeaders),
        method: req.method
      };
      if (req.body) {
        options['body'] = req.body;
      }
      return request(options, function(error, response, body) {
        var header, value, _ref1;
        if (error) {
          return next(error);
        }
        res.statusCode = response.statusCode;
        _ref1 = response.headers;
        for (header in _ref1) {
          value = _ref1[header];
          res.setHeader(header, value);
        }
        if (/text\/html/i.test(response.headers['content-type'])) {
          return filter(body, function(clean) {
            return res.end(clean);
          });
        } else {
          return res.end(body);
        }
      });
    };

    return Boomerang;

  })();

  exports.createServer = function(options) {
    return new Boomerang(options);
  };

}).call(this);
